const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_UNAUTHORISED_REQUEST = 401;
const ERROR_CODE_FORBINNED = 403;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_CONFLICT_REQUEST = 409;
const ERROR_CODE_INTERNAL = 500;

module.exports = {
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_UNAUTHORISED_REQUEST,
  ERROR_CODE_FORBINNED,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_CONFLICT_REQUEST,
  ERROR_CODE_INTERNAL,
};
